// src/data/CategoryOptions.js

const CategoryOptions = [
  // --- Design & Architecture ---
  "Architecture",
  "Urban Planning",
  "Interior Design",
  "Landscape Architecture",
  "Construction Management",
  "Civil Engineering Design",
  "Mechanical Design",
  "Electrical Design",
  "Structural Engineering",
  "Sustainable Architecture",
  "Product Design",
  "3D Visualization / CAD Drafting",

  // --- Technology & IT ---
  "Software Development",
  "Web Development",
  "Mobile App Development",
  "UI/UX Design",
  "Data Science",
  "Artificial Intelligence / Machine Learning",
  "Cyber Security",
  "Database Administration",
  "Cloud Computing",
  "DevOps",
  "IT Support",
  "Blockchain Development",
  "Game Development",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "AR/VR Development",
  "Embedded Systems",
  "IT Project Management",
  "Network Administration",
  "System Analysis",

  // --- Business & Management ---
  "Business Development",
  "Project Management",
  "Operations Management",
  "Human Resources (HR)",
  "Administration",
  "Procurement",
  "Office Management",
  "Customer Relationship Management (CRM)",
  "Entrepreneurship",
  "Management Consulting",
  "Strategic Planning",
  "Supply Chain Management",
  "Risk Management",
  "Corporate Strategy",

  // --- Marketing & Sales ---
  "Digital Marketing",
  "SEO / SEM",
  "Social Media Marketing",
  "Sales Executive",
  "Marketing Manager",
  "Brand Management",
  "Content Marketing",
  "Public Relations (PR)",
  "Telemarketing",
  "Email Marketing",
  "Influencer Marketing",
  "Affiliate Marketing",
  "Market Research Analyst",
  "Business Analyst",
  "Advertising / Media Planning",
  "E-commerce Management",

  // --- Finance & Accounting ---
  "Accounting",
  "Finance",
  "Auditing",
  "Taxation",
  "Investment Banking",
  "Financial Analysis",
  "Bookkeeping",
  "Insurance",
  "Payroll Management",
  "Budgeting and Forecasting",
  "Wealth Management",
  "Credit Analyst",
  "Loan Officer",
  "FinTech Specialist",

  // --- Education & Training ---
  "Teacher",
  "Lecturer / Professor",
  "Education Consultant",
  "Trainer / Instructor",
  "Curriculum Developer",
  "Academic Coordinator",
  "Online Tutor",
  "Research Assistant",
  "E-Learning Developer",
  "School Administrator",

  // --- Healthcare & Medical ---
  "Doctor",
  "Nurse",
  "Pharmacist",
  "Medical Technician",
  "Healthcare Administration",
  "Psychologist",
  "Dentist",
  "Physiotherapist",
  "Nutritionist / Dietitian",
  "Medical Researcher",
  "Public Health Officer",
  "Veterinarian",

  // --- Creative & Media ---
  "Graphic Design",
  "Video Editing",
  "Photography",
  "Animation",
  "Copywriting",
  "Journalism",
  "Media Production",
  "Content Creation",
  "Creative Director",
  "Film / Video Production",
  "Script Writing",
  "Podcast Production",
  "Voice Over Artist",
  "Fashion Design",
  "Illustration",
  "Art Direction",

  // --- Engineering & Technical ---
  "Civil Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Chemical Engineer",
  "Industrial Engineer",
  "Quality Assurance",
  "Maintenance Technician",
  "Automation Engineer",
  "Robotics Engineer",
  "Instrumentation Engineer",
  "Power Plant Engineer",
  "Aerospace Engineer",
  "Marine Engineer",
  "Biomedical Engineer",

  // --- Logistics & Supply Chain ---
  "Supply Chain Management",
  "Warehouse Operations",
  "Inventory Control",
  "Transportation",
  "Import / Export",
  "Fleet Management",
  "Procurement Officer",
  "Distribution Manager",
  "Logistics Coordinator",

  // --- Legal & Compliance ---
  "Lawyer / Legal Advisor",
  "Compliance Officer",
  "Paralegal",
  "Contract Management",
  "Corporate Law",
  "Intellectual Property Law",
  "Legal Researcher",
  "Policy Analyst",

  // --- Hospitality & Tourism ---
  "Hotel Management",
  "Front Desk / Reception",
  "Event Planning",
  "Travel Consultant",
  "Chef / Cook",
  "Housekeeping",
  "Food & Beverage Management",
  "Tour Guide",
  "Restaurant Management",
  "Customer Service Executive",

  // --- Science & Research ---
  "Research Scientist",
  "Lab Technician",
  "Chemist",
  "Biologist",
  "Environmental Scientist",
  "Geologist",
  "Physics Researcher",
  "Astronomer",

  // --- Energy & Environment ---
  "Renewable Energy Engineer",
  "Solar Energy Technician",
  "Wind Energy Engineer",
  "Environmental Engineer",
  "Sustainability Consultant",
  "Water Resource Management",
  "Waste Management",
  "Climate Analyst",

  // --- Manufacturing & Production ---
  "Production Supervisor",
  "Quality Control Inspector",
  "Machine Operator",
  "Product Engineer",
  "Manufacturing Manager",
  "Industrial Safety Officer",
  "Textile Engineer",
  "Packaging Engineer",

  // --- Security & Defense ---
  "Security Officer",
  "Surveillance Operator",
  "Fire Safety Officer",
  "Defense Analyst",
  "Police / Law Enforcement",
  "Intelligence Analyst",

  // --- Agriculture & Farming ---
  "Agricultural Engineer",
  "Farm Manager",
  "Horticulturist",
  "Agronomist",
  "Veterinary Assistant",
  "Food Technologist",

  // --- Customer Support & Services ---
  "Customer Support",
  "Call Center Representative",
  "Help Desk Agent",
  "Technical Support",
  "Client Relationship Manager",
  "After Sales Support",

  // --- Skilled Trades & Labor ---
  "Driver",
  "Electrician",
  "Plumber",
  "Mechanic",
  "Carpenter",
  "Welder",
  "Painter",
  "Mason",
  "Tailor / Stitcher",
  "Technician (AC / Refrigeration)",

  // --- Government & NGO ---
  "Public Administrator",
  "NGO Coordinator",
  "Social Worker",
  "Community Development Officer",
  "Policy Maker",
  "Government Officer",

  // --- Remote / Freelance Work ---
  "Freelance Developer",
  "Remote Virtual Assistant",
  "Online Customer Support",
  "Remote Designer",
  "Remote Content Writer",
  "Remote Data Entry",

  // --- Emerging Fields ---
  "Data Engineer",
  "Prompt Engineer (AI)",
  "Ethical Hacker",
  "AI Trainer",
  "Cloud Architect",
  "Cybersecurity Analyst",
  "Digital Transformation Specialist",
  "Metaverse Developer",
  "IoT Specialist",
  "Quantum Computing Researcher",

  // --- Others / Miscellaneous ---
  "Entrepreneur",
  "Internship",
  "Volunteer Work",
  "Apprenticeship",
  "Others",
];

export default CategoryOptions;
